export namespace Configuracion {
  export const hasNotificacion = "seguridad"
  export const mensajeCambioClave = "Su contraseña ha sido actualizada correctamente. Si no ha sido usted, la puede recuperar mediante la funcionalidad del sistema con su correo electrónico"
  export const mensajeCreacionUsuario = "Se ha registrado correctamente en el sistema de validación, su correo servirá como usuario y su contraseña es: "
  export const mensajeRecuperarClave = "Su nueva clave generada para el sistema es: "
  export const urlCorreo = "http://localhost:5000/correo"
  export const urlMensajeTexto = "http://localhost:5000/sms"
  export const asuntoCambioClave = "Cambio de contraseña"
  export const asuntoCreacionUsuario = "Registro en el sistema"
  export const asuntoInvitacionJurado = "Invitacion para ser jurado"
  export const saludo = "Hola"
  export const destinoArg = "destino"
  export const asuntoArg = "asunto"
  export const saludoArg = "saludo"
  export const mensajeArg = "mensaje"
  export const hashArg = "hash"

  export const mensajeCreacionSolicitud = "Se ha registrado correctamente su solicitud en el sistema de validación: <br />"
  export const asuntoCreacionSolicitud = "Registro de solicitud en el sistema"
  export const fechasolicitudArg = "<strong> Fecha de la solicitud: </strong>"
  export const nombretrabajoArg = "<br /> <strong> Nombre del trabajo:</strong>"
  export const modalidadArg = " <br /> <strong>Modalidad:</strong>"
  export const comiteArg = "<br /> <strong>Comite:</strong>"
  export const lineaArg = "<br /> <strong>Linea de Investigación:</strong>"
  export const archivoArg = "<br /> <strong> Archivo:</strong>"
  export const descripcionArg = "<br /> <strong> Descripción del trabajo:</strong>"

  export const mensajeInvitacionJurado = "Ha sido invitado por parte del sistema de validación académica para ser jurado: "
}
